name: Sync Docker Compose Installers

on:
  schedule:
    - cron: '0 0 * * *'   # 每天0点执行
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up downloads directory
        run: mkdir -p downloads

      - name: Set release tag as date
        run: echo "RELEASE_TAG=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Download Linux installers and related files
        run: |
          curl -fsSL -o downloads/docker-compose-linux-x86_64 https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
          curl -fsSL -o downloads/docker-compose-linux-aarch64 https://github.com/docker/compose/releases/latest/download/docker-compose-linux-aarch64
          curl -fsSL -o downloads/docker-compose-linux-armv6 https://github.com/docker/compose/releases/latest/download/docker-compose-linux-armv6
          curl -fsSL -o downloads/docker-compose-linux-armv7 https://github.com/docker/compose/releases/latest/download/docker-compose-linux-armv7
          curl -fsSL -o downloads/docker-compose-linux-ppc64le https://github.com/docker/compose/releases/latest/download/docker-compose-linux-ppc64le
          curl -fsSL -o downloads/docker-compose-linux-riscv64 https://github.com/docker/compose/releases/latest/download/docker-compose-linux-riscv64
          curl -fsSL -o downloads/docker-compose-linux-s390x https://github.com/docker/compose/releases/latest/download/docker-compose-linux-s390x

      - name: Download macOS installers and related files
        run: |
          curl -fsSL -o downloads/docker-compose-darwin-x86_64 https://github.com/docker/compose/releases/latest/download/docker-compose-darwin-x86_64
          curl -fsSL -o downloads/docker-compose-darwin-aarch64 https://github.com/docker/compose/releases/latest/download/docker-compose-darwin-aarch64

      - name: Download Windows installers and related files
        run: |
          curl -fsSL -o downloads/docker-compose-windows-x86_64.exe https://github.com/docker/compose/releases/latest/download/docker-compose-windows-x86_64.exe
          curl -fsSL -o downloads/docker-compose-windows-aarch64.exe https://github.com/docker/compose/releases/latest/download/docker-compose-windows-aarch64.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Docker Compose Installers (${{ env.RELEASE_TAG }})
          tag_name: ${{ env.RELEASE_TAG }}
          files: downloads/*
          body: |
            官方Docker Compose安装包，每日自动同步
            - Linux 多平台及架构
            - macOS Intel / Apple Silicon
            - Windows 多平台架构
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
