name: Sync Docker Compose Installers
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        run: |
          mkdir -p downloads
          echo "RELEASE_TAG=latest" >> $GITHUB_ENV
      - name: Download Linux installer
        run: |
          curl -fsSL https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64 -o downloads/docker-compose-Linux-x86_64
      - name: Download Windows installer
        run: |
          curl -fsSL https://github.com/docker/compose/releases/latest/download/docker-compose-Windows-x86_64.exe -o downloads/docker-compose-Windows-x86_64.exe
      - name: Create downloads directory
        run: mkdir -p downloads
      - name: Download Mac installer
        run: |
          curl -fsSL https://github.com/docker/compose/releases/latest/download/docker-compose-darwin-x86_64 -o downloads/docker-compose-Darwin-x86_64
          curl -fsSL https://github.com/docker/compose/releases/latest/download/docker-compose-darwin-arm64 -o downloads/docker-compose-Darwin-arm64
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Docker Compose Installers (Latest)
          tag_name: ${{ env.RELEASE_TAG }}
          files: downloads/*
          overwrite: true
          body: |
            官方Docker Compose安装包，每日自动同步
            - Linux: docker-compose-Linux-x86_64
            - Windows: docker-compose-Windows-x86_64.exe
            - Mac Intel: docker-compose-Darwin-x86_64
            - Mac Apple Silicon: docker-compose-Darwin-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Git for Gitee
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote add gitee https://${{ secrets.GITEE_USERNAME }}:${{ secrets.GITEE_TOKEN }}@gitee.com/ianwusb/docker-compose-installer.git
      - name: Push to Gitee
        run: |
          git push gitee main
          git push gitee --tags