name: Docker Installer Download

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天23点执行

permissions:
  contents: write

jobs:
  download_installer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download installers
      run: |
        curl -fsSL -o linux.sh "https://get.docker.com"
        curl -fsSL -o docker_desktop_installer_windows_x86_64.exe "https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe"
        curl -fsSL -o docker_desktop_installer_windows_arm64.exe "https://desktop.docker.com/win/main/arm64/Docker%20Desktop%20Installer.exe"
        curl -fsSL -o docker_desktop_installer_mac_arm64.dmg "https://desktop.docker.com/mac/main/arm64/Docker.dmg"
        curl -fsSL -o docker_desktop_installer_mac_x86_64.dmg "https://desktop.docker.com/mac/main/amd64/Docker.dmg"
        curl -fsSL -o docker_desktop_installer_linux_debian_x86_64.deb "https://desktop.docker.com/linux/main/amd64/149282/docker-desktop-4.30.0-amd64.deb"
        curl -fsSL -o docker_desktop_installer_linux_fedora_x86_64.rpm "https://desktop.docker.com/linux/main/amd64/149282/docker-desktop-4.30.0-x86_64.rpm"

    - name: Set release tag as date
      run: echo "RELEASE_TAG=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        files: |
          linux.sh
          docker_desktop_installer_windows_x86_64.exe
          docker_desktop_installer_windows_arm64.exe
          docker_desktop_installer_mac_arm64.dmg
          docker_desktop_installer_mac_x86_64.dmg
          docker_desktop_installer_linux_debian_x86_64.deb
          docker_desktop_installer_linux_fedora_x86_64.rpm
        body: |
          自动同步官方 Docker 安装器：
          - Linux 安装脚本 (get.docker.com)
          - Docker Desktop Windows (x86_64 & ARM64)
          - Docker Desktop macOS (Intel & ARM64)
          - Docker Desktop Linux (Debian & Fedora 包)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
